<a href="https://colab.research.google.com/github/akileshprabhugithub/INTERNSOFTcodefiles/blob/master/SESSION6_numpy1codefile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy

In [1]:
import numpy as np

In [3]:
a = np.arange(10)
b = np.arange(22)

In [6]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [9]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(4, 5)
20
int64
8
<class 'numpy.ndarray'>


In [12]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [13]:
b = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(b)
print(b.dtype)
print(type(b))

[1. 2. 3. 4. 5.]
float64
<class 'numpy.ndarray'>


In [17]:
c = np.eye(10)
dtype = np.int64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
d = np.linspace(-1,2,15, endpoint =True)
d

array([-1.        , -0.78571429, -0.57142857, -0.35714286, -0.14285714,
        0.07142857,  0.28571429,  0.5       ,  0.71428571,  0.92857143,
        1.14285714,  1.35714286,  1.57142857,  1.78571429,  2.        ])

In [19]:
e = np.logspace(-1,2,15, endpoint =True, base =10)
e

array([  0.1       ,   0.16378937,   0.26826958,   0.43939706,
         0.71968567,   1.17876863,   1.93069773,   3.16227766,
         5.17947468,   8.48342898,  13.89495494,  22.75845926,
        37.2759372 ,  61.05402297, 100.        ])

In [20]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [21]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [22]:
f = np.fromfunction(lambda i,j: i==j,(3,3),dtype=int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

array operations

In [28]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
a*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [30]:
a + a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [31]:
a*a

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [32]:
print(a)
b = a.transpose()
b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [33]:
a @ b

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [39]:
print(a)
print(a.sum(axis=1))
a.sum(axis=0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 3 12 21 30]


array([18, 22, 26])

In [40]:
a.sum()

66

In [41]:
print(a.min(),a.max())

0 11


universal functions

In [42]:
b = a*np.pi/12
b

array([[0.        , 0.26179939, 0.52359878],
       [0.78539816, 1.04719755, 1.30899694],
       [1.57079633, 1.83259571, 2.0943951 ],
       [2.35619449, 2.61799388, 2.87979327]])

In [43]:
c = np.cos(b)
c

array([[ 1.00000000e+00,  9.65925826e-01,  8.66025404e-01],
       [ 7.07106781e-01,  5.00000000e-01,  2.58819045e-01],
       [ 6.12323400e-17, -2.58819045e-01, -5.00000000e-01],
       [-7.07106781e-01, -8.66025404e-01, -9.65925826e-01]])

In [44]:
d = b+c
d

array([[1.        , 1.22772521, 1.38962418],
       [1.49250494, 1.54719755, 1.56781598],
       [1.57079633, 1.57377667, 1.5943951 ],
       [1.64908771, 1.75196847, 1.91386744]])

array slicing

In [45]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
arr = np.arange(100)
arr
odd = arr[1:100:2]
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [46]:
a[3]

3

In [52]:
print(a[1:4])

[1 2 3]


In [53]:
a[2:6]

array([2, 3, 4, 5])

In [54]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

multidimensional arrays

In [56]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a[1,1]

5

In [58]:
a[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [62]:
a[:,0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [65]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
c =np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
for r in c :
    print(r)
c = np.arange(12).reshape(4,3)
c

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
for e in c.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11


In [74]:
help(c.flatten())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

 copying arrays

In [75]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
b = a
b is a

True

In [77]:
b.shape = (2,5)
print(b)
a.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [78]:
b is a

True

In [79]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
a = np.arange(12)
c = a[:]
a.shape=(3,4)
print(a)
c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
c[1] = -1
print (a)
c

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
d = c[3:8]
d

array([3, 4, 5, 6, 7])

In [83]:
d[:] = 0

In [84]:
print(a)
print(c)
d

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]


array([0, 0, 0, 0, 0])

In [85]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [86]:
d = a.copy()
d[:,:] = 1
print(a)
d

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])